name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version, for example 1.2.4-pm.1
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
          node-version-file: .node-version
          run-install: |
            - args: ['--frozen-lockfile']
      - name: Set release version
        run: |
          mkdir -p gen
          printf '"%s"\n' '${{ inputs.version }}' > gen/version.json
      - run: vp run verify
      - run: vp run build
      - run: vp run create-xpi
      - id: publish-xpi
        name: Publish XPI
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ inputs.version }}
          name: v${{ inputs.version }}
          files: xpi/*.xpi
      - name: Generate update manifest
        run: vp run generate-update-manifest '${{ fromJSON(steps.publish-xpi.outputs.assets)[0].browser_download_url }}'
      - name: Publish update manifest
        uses: softprops/action-gh-release@v3
        with:
          tag_name: release
          name: release
          files: gen/update*
